[project]
name = "tt-server"
version = "0.1.0"
license = "Apache-2.0"
description = "Django server for Token Tuner"
authors = [
    {name = "@thisispalash", email = "dev@thisispalash.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4"
dependencies = [
    "django (>=6.0,<7.0)"
]

[project.urls]
homepage = "https://tokentuner.xyz/"
documentation = "https://docs.tokentuner.xyz/"
repository = "https://github.com/thisispalash/tt-monorepo"

[tool.poetry]
packages = [
    {include = "server"}
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
